### ISSUE TITLE
Can't find dicts file

### ISSUE THREAD

**Issue by mjtadema** [brisvag/gibberify#21]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/matthijs/gibberify/gibberify/__main__.py", line 55, in <module>
    main()
  File "/home/matthijs/gibberify/gibberify/__main__.py", line 42, in main
    with open(os.path.join(data, 'dicts.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/matthijs/gibberify/gibberify/data/dicts.json'

And eh well.. it's indeed not there.. I also don't see it in your repo. Maybe you forgot to add it?

**Comment by brisvag** [comment]
I took back the release because I messed up some things with the building. 

The build you are using as actually an old version that is now broken: I removed all the stuff in the `/data` directory from the repo's history, because that was a mistake since the start. Too heavy, not supposed to be in the repo in the first place.

I will mark the first release as broken to make sure other people don't have that problem!
