### ISSUE TITLE
Weird PyQt issue

### ISSUE THREAD

**Issue by mjtadema** [brisvag/gibberify#35]
```Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/matthijs/gibberify/gibberify/__init__.py", line 7, in <module>
    from .ui import gui, interactive
  File "/home/matthijs/gibberify/gibberify/ui/__init__.py", line 3, in <module>
    from .gui import gui
  File "/home/matthijs/gibberify/gibberify/ui/gui.py", line 9, in <module>
    from PyQt5.QtGui import QFontDatabase, QIcon, QFont
ModuleNotFoundError: No module named 'PyQt5.sip'```

**Comment by brisvag** [comment]
It seems to be out of our hands. For now, the "solution" was added to the readme in fae9348:
```
pip install --user --upgrade PyQt5
pip install --user --upgrade PyQt5-sip
```
